### ISSUE TITLE
Xcode project file is not committed

### ISSUE THREAD

**Issue by AlexisQapa** [Bahn-X/swift-composable-navigator#56]
# Bug description
The main Xcode project file is not committed into the repo. When cloning and opening the Example workspace there is a missing Xcode project file reference.

# Steps to reproduce 
Clone open the workspace in Example folder. Hit run.

# Expected behavior
Example should build and run.

# Environment
 - Xcode 12.4 / 12.5 beta 3
 - Swift Xcode version.

**Comment by mltbnz** [comment]
Should be solved by #57

**Comment by AlexisQapa** [comment]
Thanks, I stumbled upon the PR.
